pipeline {
    agent none

    stages {
        stage ('back-end') {
            agent {
                docker { image 'maven:3.8.4-jdk-11' }
            }
            steps {
                sh 'mvn --version'
            }
        }
        stage {'front-end'} {
            agent {
                docker { image 'node:16-alpine'}
            }
            steps {
                sh 'node --version'
            }
        }
    }
}